config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :clients
  resources :receipts
  resources :discounts
  resources :societies
  get 'menuSociedades' => 'societies#menuSociedades'
  get 'reportes'=>'societies#reportes'
  get 'membership' => 'clients#membership'

  get 'signup',to: 'users#new'
  post 'users',to: 'users#create'
  resources :users ,except: [:new]
  root  'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  

end

app/models/society.rb
class Society < ActiveRecord::Base
  has_many :discounts
  has_many :categories, through: :discounts
  belongs_to :user

  accepts_nested_attributes_for :discounts,reject_if: :all_blank,allow_destroy: true

  validates :nombre, presence: true ,length: {minimum: 3, maximum: 50}
  validates :descripcion, presence: true ,length: {minimum: 3, maximum: 300}
  validates :val_anual, presence: true
  validates :val_semestral, presence: true
  #validates :user_id, presence: true


end

app/controllers/societies_controller.rb
class SocietiesController < ApplicationController
  before_action :set_society, only: [:show, :edit, :update, :destroy]

  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
 # before_action :require_user, except: [:index, :show]
  # GET /societies
  # GET /societies.json
  def index
    @societies = Society.all
  end

  # GET /societies/1
  # GET /societies/1.json
  def show
  end

  # GET /societies/new
  def new
    @society = Society.new
  end

  # GET /societies/1/edit
  def edit
  end

  # POST /societies
  # POST /societies.json
  def create
    @society = Society.new(society_params)
    @categories=Category.all
    @society.user = current_user
    respond_to do |format|
      if @society.save
        flash[:notice] = "Felicidades has creado una sociedad"
        format.html { redirect_to @society, notice: 'Society was successfully created.' }
        format.json { render :show, status: :created, location: @society }
      else
        format.html { render :new }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /societies/1
  # PATCH/PUT /societies/1.json
  def update
    respond_to do |format|
      if @society.update(society_params)
        flash[:notice] = "Has actualizado una sociedad"
        format.html { redirect_to @society, notice: 'Society was successfully updated.' }
        format.json { render :show, status: :ok, location: @society }
      else
        format.html { render :edit }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /societies/1
  # DELETE /societies/1.json
  def destroy
    @society.destroy
    respond_to do |format|
      format.html { redirect_to societies_url, notice: 'Society was successfully destroyed.' }
      format.json { head :no_content }
    end

    end
  end
def
  menuSociedades
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_society
      @society = Society.find(params[:id])
    end

  def require_same_user
   if current_user != @society.user and !current_user.admin?
       flash[:danger] = "solo puedes editar la sociedad que hallas creado"
        redirect_to root_path
        
   end

  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def society_params
    params.require(:society).permit(:nombre, :descripcion, :val_anual, :val_semestral, :val_mensual,
                                    :discounts_attributes => [:id, :discount_porcentaje, :society_id, :category_id, :_destroy,
                                    :category_attributes => [:id, :nombre]] )
  end

app/helpers/societies_helper.rb
module SocietiesHelper
end

app/views/societies/_discount_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
    <table width="500" >
      <tr>
        <td><h5>Categoría</h5></td>
        <td> <h5>Porcentaje de Descuento</h5></td>
      </tr>
      <tr>

        <td><%= f.collection_select :category_id, Category.order(:nombre), :id, :nombre, include_blank: true%></td>
        <td> <%= f.number_field :discount_porcentaje %>
        <%=link_to_remove_association "Eliminar", f %></td>
      </tr>
    </table>
  </div>
</li>

app/views/societies/_form.html.erb
<div align="center">
<% if @society.errors.any? %>
<h2>Has cometido un error los siguientes errores te muestran porque no se ha podido crear</h2>
<ul>
 <% @society.errors.full_messages.each do |msg| %>
 <li><%= msg%></li>
 <%end %>
</ul>
<% end%>

  <h4>Sociedad <%= @society.nombre %> </h4>
<%= form_for(@society) do |f| %>
          <div align="center">
        <%= f.text_field :nombre, placeholder: "Nombre", :required=>true  %>
      </div>
      <div align="center">
        <%= f.text_area :descripcion, placeholder: "Descripción",cols:"40"  %>
      </div >
      <div align="center">
        <%= f.number_field :val_anual, placeholder: "Valor Anual"  %>
        <%= f.number_field :val_semestral, placeholder: "Valor Semestral"  %>
        <%= f.number_field :val_mensual, placeholder: "Valor Mensual"  %>
      </div><br>
        <div align="center">
      <%= link_to_add_association 'Añadir descuento', f,:discounts,
                                  'data-association-insertion-node' => "#discounts-category ol",
                                  'data-association-insertion-method' => "append",
                                  :wrap_object => Proc.new {|discount| discount.build_category; discount }%>
      <hr/>
      <fieldset id="discounts-category">
        <ol>
          <%= f.fields_for :discounts do |discount| %>
              <%= render partial: "discount_fields", locals: {f:discount} %>
          <%end%>
        </ol>
      </fieldset>
   </div>
      <div class="actions">
        <%= f.submit "Guardar"%>
      </div>
  <% end %>
</div>

app/views/societies/_society.html.erb
  <table width="1000" border="0" align="center">
    <thead>
    <tr>
      <th>Nombre Sociedad</th>
      <th>Valor Anual</th>
      <th>Valor Mensual</th>
      <th>Valor Dos Contados</th>
      <th colspan="5"></th>
    </tr>
    </thead>
    <tbody align="center">
    <% obj.each do |societies| %>
       
        <td ><%=societies.nombre %></td>
        <td><%=societies.val_anual%></td>
        <td><%=societies.val_semestral%></td>
        <td><%=societies.val_mensual%></td>
        
        <td><%= link_to image_tag('ver.png', title: 'Ver'), societies %></td>
        <%if logged_in? &&  (current_user == societies.user || current_user.admin?) %>
        <td><%= link_to image_tag('edit.png', title: 'Editar'), edit_society_path(societies) %></td>
        <td><%= link_to image_tag('eliminar.png', title: 'Eliminar'), societies, method: :delete, data: { confirm: 'Esta seguro de eliminar?' } %></td>
        <% end %>
        <tr></tr>

    <% end %>
    </tbody>
  </table>

app/views/societies/edit.html.erb
<main>
  <div align="center">
<h4 align="center">Editar</h4>
<%= render 'form' %>
<%= link_to 'Ver', @society %> |
<%= link_to 'Atras', societies_path %>
  </div>
</main>

app/views/societies/index.html.erb
<main>

  <h3 align="center">Sociedades</h3>
   <div align="left">
      <%= link_to image_tag('anadir.jpg', title: 'Nueva sociedad', :width => "30px", :height => "30px" ), new_society_path  %><br>
      <%= link_to 'Nueva Sociedad', new_society_path %>
    </div><br>
  <%= render 'society', obj:@societies %>

</main>
<%= link_to 'Crear Sociedad', new_society_path %>

app/views/societies/menuSociedades.html.erb
<!doctype html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sociedades</title>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="bootstrap-3.3.6-dist/css/stylemenu.css"/>
  <link rel="stylesheet" type="text/css" href="bootstrap-3.3.6-dist/css/index.css"/>

</head>
<body>
<main>
  <div class="content">
    <div class="inner">

      <center>  <h2>Sociedades </h2>
        <div class="btn-group" role="group">
          <p><br>
            <br/>
          </p>
        </div>
        <table width="600" border="0" align="center">
          <tbody>
          <tr>

            <td><%= link_to image_tag('afiliate.jpg', title: 'afiliar', :width => "150px", :height => "150px" ),'membership'  %><br>Afiliación a Sociedad</td>
            <td><%= link_to image_tag('pago.jpg', title: 'pago de cuota', :width => "150px", :height => "150px" ), societies_path %><br>Pago de Cuota Sociedad</td>
          </tr>
          <tr>
            <td><%= link_to image_tag('reporte.png', title: 'reporte', :width => "150px", :height => "150px" ), 'reportes' %><br> Reportes</td>
            <td><%= link_to image_tag('crudMem.png', title: 'Sociedades', :width => "150px", :height => "150px" ), societies_path %><br>Gestión de Sociedades></td>

          </tr>
          </tbody>
        </table>

        <label><br>
        </label>

      </center>
    </div>
  </div>
</main>
</body>
</html>

app/views/societies/new.html.erb
<main>

<%= render 'form' %>
  <div align="center">
<%= link_to 'Atras', societies_path %>
</div>
</main>

app/views/societies/reportes.html.erb
<!DOCTYPE html>
<html lang="en">
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<head>
    <meta charset="UTF-8">
    <title>Reportes</title>
</head>
<body>
</body>
<main>
<h1>Sociedades</h1>
<%= pie_chart Society.group(:nombre).count %>
<br><h1>Categorias</h1>
<%= pie_chart Category.group(:nombre).count %>

<br><h1>Clientes</h1>
<%= pie_chart Client.group(:nombre).count %>
</main>
</html>

app/views/societies/show.html.erb
<main>
  <br><br>
  <div align="center">
    <h4>Sociedad <%= @society.nombre %></h4>
    <%= @society.descripcion %>
  </div>

  <div align="center">
    <table align="center", width="500">
      <tr>
        <td><h4>Precio Anual</h4></td>
        <td><h4>Precio Semestral</h4></td>
        <td><h4>Precio Mensual</h4></td>
      </tr>
      <tr>
        <td>$<%= @society.val_anual %></td>
        <td>$<%= @society.val_semestral%></td>
        <td>$<%= @society.val_mensual%></td>
      </tr>
    </table>
  </div>

  <div align="center" >
    <table width="500" >
      <tr>
        <td><h4>Categoría</h4></td>
        <td> <h4>Descuento</h4></td>
      </tr>
      <tr><td> <% @society.categories.each do |category|%>
            <h5><%= link_to category.nombre, category %></h5><% end %></td>
        <td > <% @society.discounts.each do |discount|%>
              <h5 ><%= discount.discount_porcentaje%></h5><% end %></td>
      </tr>
    </table>
  </div>
  <div align="center">
      <%= link_to "Atras", societies_path(@society) %>
    <% if logged_in? &&  (@society.user == current_user || current_user.admin?) %>
    <%= link_to "Editar", edit_society_path(@society) %>
    <% end %>

  </div>
</main>