config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :clients
  resources :receipts
  resources :discounts
  resources :societies
  get 'menuSociedades' => 'societies#menuSociedades'
  get 'reportes'=>'societies#reportes'
  get 'membership' => 'clients#membership'

  get 'signup',to: 'users#new'
  post 'users',to: 'users#create'
  resources :users ,except: [:new]
  root  'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  belongs_to :client
  belongs_to :society
  belongs_to :forma_de_pago
  belongs_to :user
  has_attached_file :soporte, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :soporte, content_type: /\Aimage\/.*\z/


  validates :fecha, presence: true
  validates :valor_total, presence: true

  #validates :user_id, presence: true


end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]
#before_action :require_user
  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params.require(:receipt).permit(:fecha, :valor_total, :soporte)
    end
end

app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>

<% if @receipt.errors.any? %>
<h2>Has cometido un error los siguientes errores te muestran porque no se ha podido crear</h2>
<ul>
 <% @receipt.errors.full_messages.each do |msg| %>
 <li><%= msg%></li>
 <%end %>
</ul>
<% end%>

  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :valor_total %><br>
    <%= f.text_field :valor_total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing Receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<head>
  <meta charset="utf-8">
  <title>Gestion Sociedades</title>

</head>
<main >
  <p id="notice"><%= notice %></p>

  <h1 align="center">Recibos</h1>
<div align="center">
  <table width="500" align="center">
    <thead align="center">
    <tr>
      <th align="left">Fecha</th>
      <th align="right">Valor</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @receipts.each do |receipt| %>
        <tr >
          <td align="left"><%= receipt.fecha %></td>
          <td align="right"><%= receipt.valor_total %></td>
          <td align="right"><%= link_to 'Ver', receipt %></td>
         <!-- <td align="right"><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
          <td align="right"><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

  <br>

  <!--<%= link_to 'New Receipt', new_receipt_path %>-->

</main>

app/views/receipts/new.html.erb
<h1>New Receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<head>
  <meta charset="utf-8">
  <title>Gestion Sociedades</title>

</head>
<main>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Fecha:</strong>
    <%= @receipt.created_at %>

  </p>

  <p>
    <strong>Valor</strong>
    <%= @receipt.valor_total %>
  </p>
  <h5><%= @receipt.client_id %></h5>
  <h5><%= @receipt.society_id %></h5>
  <div>
    <%= image_tag @receipt.soporte.url() %>
  </div>



   |
  <%= link_to 'Back', receipts_path %>



</main>